version: '2'
services:
  db:
    image: mysql:5.7
    container_name: diary
    restart: always
    ports:
      - "11111:3306"
    environment:
      - MYSQL_USER=diary
      - MYSQL_DATABASE=diary
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8']
    networks:
      main:
        aliases:
          - paperTest
networks:
  main:
